---
language: minimal

services:
- docker

env:
  global:
  - DOCKER_IMAGE=informaticsmatters/fragalysis-nery

stages:
- name: publish
  if: tag IS present OR branch == master

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

matrix:
  include:

  - stage: publish
    name: Publish latest
    script:
    - docker build -t "$DOCKER_IMAGE":latest .
    - docker push "$DOCKER_IMAGE":latest
    if: tag IS NOT present

  - stage: publish
    name: Publish tag
    script:
    - docker build -t "$DOCKER_IMAGE":"$TRAVIS_TAG" .
    - docker push "$DOCKER_IMAGE":"$TRAVIS_TAG"
    if: tag IS present
